export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: '/qVNACrSwu8RCgf9loLKfTv0mDeq.jpg',
    id: 137040,
    name: 'Black Knight',
    original_language: 'ko',
    original_name: '택배기사',
    overview:
      'In a dystopian 2071 devastated by air pollution, the survival of humanity depends on the Black Knights — and they’re far from your average delivery men.',
    poster_path: '/78W8tIM3PgIO6OIMfugi6p1GHNT.jpg',
    media_type: 'tv',
    genre_ids: [10765, 10759, 18],
    popularity: 110.457,
    first_air_date: '2023-05-12',
    vote_average: 9.6,
    vote_count: 39,
    origin_country: ['KR'],
  },
  {
    adult: false,
    backdrop_path: '/n5FPNMJ0eRoiQrKGfUQQRAZeaxg.jpg',
    id: 125988,
    name: 'Silo',
    original_language: 'en',
    original_name: 'Silo',
    overview:
      'In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.',
    poster_path: '/1NxaSn4ver4jIvLeD7YF8cTlZjB.jpg',
    media_type: 'tv',
    genre_ids: [10765, 18],
    popularity: 439.508,
    first_air_date: '2023-05-04',
    vote_average: 8.792,
    vote_count: 48,
    origin_country: ['GB', 'US'],
  },
  {
    adult: false,
    backdrop_path: '/hbXUwGcAQmCnYfzLYanlzzuJJmS.jpg',
    id: 155534,
    name: 'City on Fire',
    original_language: 'en',
    original_name: 'City on Fire',
    overview:
      'A college student is shot in Central Park on July 4, 2003. The investigation connects a series of mysterious citywide fires, the downtown music scene, and a wealthy uptown real estate family fraying under the strain of the many secrets they keep.',
    poster_path: '/lGzN8SgwlQMYn5uUI0pzG9EfXSD.jpg',
    media_type: 'tv',
    genre_ids: [18, 9648],
    popularity: 54.048,
    first_air_date: '2023-05-11',
    vote_average: 7.5,
    vote_count: 5,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/3cgRI0hOq3dYyezSYrsfdmqxtMw.jpg',
    id: 114922,
    name: 'Citadel',
    original_language: 'en',
    original_name: 'Citadel',
    overview:
      'What if you lost your memory? What if a spy didn’t know they were a spy? Years ago, the top agents of Citadel, Mason Kane and Nadia Sinh, had their minds wiped. But, they’re called back to action as sinister forces emerge from the past. With the help of spymaster Bernard Orlick, these former lovers must remember the past to save the future.',
    poster_path: '/AcrDB32TqpAGwvQFbICALGxSzn3.jpg',
    media_type: 'tv',
    genre_ids: [18, 80, 10759],
    popularity: 289.657,
    first_air_date: '2023-04-27',
    vote_average: 7.888,
    vote_count: 76,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg',
    id: 85937,
    name: 'Demon Slayer: Kimetsu no Yaiba',
    original_language: 'ja',
    original_name: '鬼滅の刃',
    overview:
      'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
    poster_path: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    media_type: 'tv',
    genre_ids: [16, 10759, 10765],
    popularity: 339.424,
    first_air_date: '2019-04-06',
    vote_average: 8.703,
    vote_count: 5169,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/2q4aPLPu7XqAbDe8JXcRyK5i6g9.jpg',
    id: 224387,
    name: 'Queen Cleopatra',
    original_language: 'en',
    original_name: 'Queen Cleopatra',
    overview:
      "As Egypt's last pharaoh, Cleopatra fights to protect her throne, family and legacy in this docuseries featuring reenactments and expert interviews.",
    poster_path: '/9j0u72TrqdVEFDTj7uG5KOFwbSg.jpg',
    media_type: 'tv',
    genre_ids: [99, 10765],
    popularity: 98.257,
    first_air_date: '2023-05-10',
    vote_average: 3.196,
    vote_count: 56,
    origin_country: ['GB'],
  },
  {
    adult: false,
    backdrop_path: '/98e4b1kJapAauRjjFXNIA4Xqrv8.jpg',
    id: 93812,
    name: 'The Great',
    original_language: 'en',
    original_name: 'The Great',
    overview:
      'A genre-bending, anti-historical ride through 18th century Russia following the rise of Catherine the Nothing to Catherine the Great and her explosive relationship with husband Peter, the emperor of Russia.',
    poster_path: '/tpz9UQ3hUwYufNcKWVW00FCjWyc.jpg',
    media_type: 'tv',
    genre_ids: [18, 35],
    popularity: 150.75,
    first_air_date: '2020-05-15',
    vote_average: 8.168,
    vote_count: 839,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/ggqBUyRMldy2JvPGmR80zMBUx5V.jpg',
    id: 100349,
    name: 'Mulligan',
    original_language: 'en',
    original_name: 'Mulligan',
    overview:
      'In this satirical comedy, when most of Earth is destroyed by aliens, can a few survivors rebuild what’s left of America and form a more perfect union?',
    poster_path: '/t4jMaK7u5S4p5sEW76GmBNQfE90.jpg',
    media_type: 'tv',
    genre_ids: [16, 35],
    popularity: 70.619,
    first_air_date: '2023-05-12',
    vote_average: 8.25,
    vote_count: 4,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/a6ptrTUH1c5OdWanjyYtAkOuYD0.jpg',
    id: 37854,
    name: 'One Piece',
    original_language: 'ja',
    original_name: 'ワンピース',
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster_path: '/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg',
    media_type: 'tv',
    genre_ids: [10759, 35, 16],
    popularity: 101.405,
    first_air_date: '1999-10-20',
    vote_average: 8.714,
    vote_count: 3720,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/zrMCOQnzIgGyBtGCdMPom9bOw0r.jpg',
    id: 62286,
    name: 'Fear the Walking Dead',
    original_language: 'en',
    original_name: 'Fear the Walking Dead',
    overview:
      'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
    poster_path: '/zyshFjmlDXSzfns2Qk81cfIFfPP.jpg',
    media_type: 'tv',
    genre_ids: [10759, 18],
    popularity: 287.035,
    first_air_date: '2015-08-23',
    vote_average: 7.7,
    vote_count: 4448,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/LYIWbxV9q5sW1EjdIdeCjBdOOB.jpg',
    id: 127948,
    name: "Class of '09",
    original_language: 'en',
    original_name: "Class of '09",
    overview:
      'Set in three distinct points in time, follow a class of FBI agents who grapple with immense changes as the U.S. criminal justice system is altered by artificial intelligence.',
    poster_path: '/tHA5i8GfQ9qyzDpUJj1upBGu7lt.jpg',
    media_type: 'tv',
    genre_ids: [18, 9648, 80],
    popularity: 100.203,
    first_air_date: '2023-05-10',
    vote_average: 8.455,
    vote_count: 11,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/dkKEpUCjGEFH5q3GcAGaWG3o2N2.jpg',
    id: 196454,
    name: 'Queen Charlotte: A Bridgerton Story',
    original_language: 'en',
    original_name: 'Queen Charlotte: A Bridgerton Story',
    overview:
      'The story of how the young Queen Charlotte’s marriage to King George sparked both a great love story and a societal shift, creating the world of the Ton inherited by the characters in Bridgerton.',
    poster_path: '/eR7btjpvOugivUYSoEsD2iAOYsJ.jpg',
    media_type: 'tv',
    genre_ids: [18],
    popularity: 409.237,
    first_air_date: '2023-05-04',
    vote_average: 7.959,
    vote_count: 122,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/htZNH4PJwJCfiw6dbtpyXCuglXz.jpg',
    id: 95558,
    name: 'The Power',
    original_language: 'en',
    original_name: 'The Power',
    overview:
      'The world of The Power is our world, but for one twist of nature. Suddenly teenage girls develop the power to electrocute people at will. Following remarkable characters from London to Seattle, Nigeria to Eastern Europe, the Power evolves from a tingle in teenagers’ collarbones to a complete reversal of power balance.',
    poster_path: '/pTeb4EsTy3hoVFpg9FnLIF3glZ5.jpg',
    media_type: 'tv',
    genre_ids: [10765, 9648, 18],
    popularity: 90.57,
    first_air_date: '2023-03-30',
    vote_average: 6.722,
    vote_count: 27,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/q3UGWifvIpdey1T2efX4dSmbZpU.jpg',
    id: 124364,
    name: 'From',
    original_language: 'en',
    original_name: 'From',
    overview:
      'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
    poster_path: '/pnrv8tfOcWxu4CrB8N7xK0jYJsR.jpg',
    media_type: 'tv',
    genre_ids: [9648, 18, 10765],
    popularity: 392.752,
    first_air_date: '2022-02-20',
    vote_average: 8.278,
    vote_count: 315,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/iRxHhvktvbm9ybi6NLgF1yMmwP4.jpg',
    id: 194573,
    name: 'The Muppets Mayhem',
    original_language: 'en',
    original_name: 'The Muppets Mayhem',
    overview:
      'The Electric Mayhem Band goes on an epic musical journey to finally record their first studio album. With the help of a driven young music executive, Nora, the old-school Muppet band comes face to face with the current day music scene as they try to finally go platinum.',
    poster_path: '/fxJrS7cXn5hK09xDuqp7isQOFXX.jpg',
    media_type: 'tv',
    genre_ids: [35, 10751],
    popularity: 53.428,
    first_air_date: '2023-05-10',
    vote_average: 5.5,
    vote_count: 13,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/qA37cB9PdiOrCmECXjQXy0ip23x.jpg',
    id: 225008,
    name: 'The Long Season',
    original_language: 'zh',
    original_name: '漫长的季节',
    overview:
      "In the small town of Hualin, taxi driver Wang Xiang had the chance to meet the person he both most wanted and feared to encounter in his life. Meeting this person would require an explanation, for himself and for his son.\n\nWang Xiang was full of confidence as a train driver, but struggled with the trivialities of his own small family. The factory was on the verge of collapse, and the discovery of an unidentified dismembered body struck Wang Xiang's mind.\n\nFor twenty years, Wang Xiang was trapped in three different eras, chasing after the truth that crossed the past, present, and future, all to solve an unsolved mystery. When the answer was finally revealed, time and space merged into one, and only the dirge of fate remained in the long seasons.",
    poster_path: '/rM5Y0ziZbmpkqW1db2HK3xrzTXj.jpg',
    media_type: 'tv',
    genre_ids: [18, 10751, 80, 9648],
    popularity: 45.025,
    first_air_date: '2023-04-22',
    vote_average: 8.483,
    vote_count: 29,
    origin_country: ['CN'],
  },
  {
    adult: false,
    backdrop_path: '/sKuELD505doZKdOrsJFq36Qy327.jpg',
    id: 201019,
    name: 'Tale of the Nine Tailed 1938',
    original_language: 'ko',
    original_name: '구미호뎐1938',
    overview:
      'A K-fantasy action unfolds as the Nine-tailed fox makes a crash landing in the year 1938, an era of chaos, and he struggles to return to the present.',
    poster_path: '/hwntWLbs4SQqoHmF3pdod4VRCIx.jpg',
    media_type: 'tv',
    genre_ids: [10765, 10759, 18],
    popularity: 131.099,
    first_air_date: '2023-05-06',
    vote_average: 7.8,
    vote_count: 6,
    origin_country: ['KR'],
  },
  {
    adult: false,
    backdrop_path: '/fFydbDHn3XAC7nyMj4fRT6L18Wx.jpg',
    id: 104716,
    name: 'Sisters Who Make Waves',
    original_language: 'zh',
    original_name: '乘风破浪的姐姐',
    overview: '',
    poster_path: '/d6YmZcTKGpIlBifdQZhG2K2RfFo.jpg',
    media_type: 'tv',
    genre_ids: [10764],
    popularity: 50.56,
    first_air_date: '2020-06-12',
    vote_average: 7.5,
    vote_count: 4,
    origin_country: ['CN'],
  },
  {
    adult: false,
    backdrop_path: '/pGtvfzfIRCsiudAWlzlGZ74co5l.jpg',
    id: 124800,
    name: 'Love & Death',
    original_language: 'en',
    original_name: 'Love & Death',
    overview:
      'The true story of Candy and Pat Montgomery and Betty and Allan Gore – two churchgoing couples enjoying their small town Texas life… until an extramarital affair leads somebody to pick up an axe.',
    poster_path: '/8WchbT0UPQeo3PZ6G01fhccYaQB.jpg',
    media_type: 'tv',
    genre_ids: [80, 18],
    popularity: 164.516,
    first_air_date: '2023-04-27',
    vote_average: 8.492,
    vote_count: 60,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/wImNeqxKsqmJ5OBw8j3I37GNFN3.jpg',
    id: 97546,
    name: 'Ted Lasso',
    original_language: 'en',
    original_name: 'Ted Lasso',
    overview:
      'Ted Lasso, an American football coach, moves to England when he’s hired to manage a soccer team—despite having no experience. With cynical players and a doubtful town, will he get them to see the Ted Lasso Way?',
    poster_path: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg',
    media_type: 'tv',
    genre_ids: [35, 18],
    popularity: 185.372,
    first_air_date: '2020-08-14',
    vote_average: 8.47,
    vote_count: 1005,
    origin_country: ['GB'],
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: '/aUgF7RY2B8JSuYSUB96Gn5vgEe9.jpg',
    id: 135670,
    name: 'Dhindora',
    original_language: 'hi',
    original_name: 'ढिंढोरा',
    overview:
      "It revolves around Bhuvan and his family's everyday lives, when an unexpected purchase leads to a series of events and depicts every common man's larger than life dreams.",
    poster_path: '/i6RJyrJRps31JKWGZVKow6ZbSZM.jpg',
    media_type: 'tv',
    genre_ids: [35, 18],
    popularity: 2.76,
    first_air_date: '2021-10-14',
    vote_average: 4.8,
    vote_count: 20,
    origin_country: ['IN'],
  },
  {
    adult: false,
    backdrop_path: '/bqhPsRCJBkmjrQFJzrYmnMm3KaJ.jpg',
    id: 46184,
    name: 'Campione!',
    original_language: 'ja',
    original_name: 'カンピオーネ!',
    overview:
      'Godo Kusanagi, a high school student that kills a god, claiming its power and title of Campione, to slay other gods.',
    poster_path: '/h46tgmaPjq7ojhgqlR7lE8VxVfm.jpg',
    media_type: 'tv',
    genre_ids: [16, 35, 10765],
    popularity: 13.071,
    first_air_date: '2012-07-06',
    vote_average: 8.297,
    vote_count: 74,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/gFkHcIh7iE5G0oVOgpmY8ONQjhl.jpg',
    id: 60735,
    name: 'The Flash',
    original_language: 'en',
    original_name: 'The Flash',
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    poster_path: '/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg',
    media_type: 'tv',
    genre_ids: [18, 10765],
    popularity: 389.357,
    first_air_date: '2014-10-07',
    vote_average: 7.798,
    vote_count: 10399,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/ter4f3edK6YTlTQzR1wWZiQtj1x.jpg',
    id: 77076,
    name: 'The Joel McHale Show with Joel McHale',
    original_language: 'en',
    original_name: 'The Joel McHale Show with Joel McHale',
    overview:
      "Trending news, pop culture, social media, original videos and more come together in host Joel McHale's weekly comedy commentary show.",
    poster_path: '/xKcjHKJzaiMn1viUhMvQlYntQWL.jpg',
    media_type: 'tv',
    genre_ids: [35, 10767],
    popularity: 9.325,
    first_air_date: '2018-02-18',
    vote_average: 6.019,
    vote_count: 27,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/8RklDvHB7RBFsojxmyjSdG68CRT.jpg',
    id: 67868,
    name: 'The Mystic Nine',
    original_language: 'zh',
    original_name: '老九门',
    overview:
      "The drama is a prequel to The Lost Tomb in which the story focuses  on the exploits of the nine grave robbing families in the 1940s. With  the help of his friends Fortune Teller Qi Tie Zue and Opera Singer Er  Yue Hong, General Zhang Qi Shan entered into a strange mine to discover a  mysterious ancient tomb. After many untold dangers, he uncovered a  Japanese plot to kill the residents of Changsha city. The men banded  together to stop the Japanese's plot, thereby saving their city.",
    poster_path: '/u6Sw6vawU1jved4aBIDa3Ft9yIw.jpg',
    media_type: 'tv',
    genre_ids: [9648, 10759],
    popularity: 22.102,
    first_air_date: '2016-07-04',
    vote_average: 8.2,
    vote_count: 5,
    origin_country: ['CN'],
  },
  {
    adult: false,
    backdrop_path: '/oIz5dCcbv5QqITLPnJuum4MWAur.jpg',
    id: 63014,
    name: 'I Am Cait',
    original_language: 'en',
    original_name: 'I Am Cait',
    overview:
      'Caitlyn Jenner\'s first public appearance since her transition included making an impassioned, heartfelt speech at the ESPY Awards about the need for understanding transgender issues and "accepting people for who they are." For her part, Caitlyn -- formerly known as Bruce Jenner -- eagerly welcomes the responsibility to educate people. Follow Caitlyn Jenner\'s life as a transgender woman, telling her intimate story as she seeks out her "new normal," while offering a better understanding of many of life\'s challenges. Most of all, Caitlyn looks forward to living for the first time as the person she feels she was born to be. The docu-series also explores what her transition means for the people closest to her, including her children and stepchildren, and how those relationships are affected.',
    poster_path: '/m27KexNPrOREbxw4413BUvQijqA.jpg',
    media_type: 'tv',
    genre_ids: [99, 10764],
    popularity: 5.144,
    first_air_date: '2015-07-26',
    vote_average: 5.6,
    vote_count: 24,
    origin_country: ['US'],
  },
  {
    adult: false,
    backdrop_path: '/p7D1IjxilgQGBoo42YZaAkcTFIQ.jpg',
    id: 9161,
    name: 'Dirty Pair',
    original_language: 'ja',
    original_name: 'ダーティペア',
    overview:
      'Kei and Yuri are the two members of Trouble Consultant team 234, code named "Lovely Angels". Almost every mission they are involved with ends up in disaster, though not failure: They typically capture their target fugitive, but end up destroying a city in the process, earning the nickname the "Dirty Pair", a moniker they openly hate being called. They are always cleared of any wrongdoing by the 3WA\'s Central Computer because the extreme collateral damage is never actually determined to be their fault, although their mere presence tends to worsen the situations for which they are hired. In some but not all continuities, they have joint extrasensory perception powers, usually limited to precognition. This talent was the reason they were recruited in the first place.',
    poster_path: '/8j1jbA6hXDnktWD9P4woHiWHRhw.jpg',
    media_type: 'tv',
    genre_ids: [16, 35, 10759, 10765],
    popularity: 8.398,
    first_air_date: '1985-07-15',
    vote_average: 7.9,
    vote_count: 24,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/88Rd5sdhAVJuG9H7eTA4nqddz4t.jpg',
    id: 42444,
    name: 'Saint Seiya',
    original_language: 'ja',
    original_name: '聖闘士星矢',
    overview:
      'Ages ago, the goddess Athena was served by fighters called Saints who channeled the power of the Cosmos within them. Now a youth named Seiya has trained to become a Saint himself by earning the mystical Cloth of Pegasus. He is joined by other Saints with Cloths of their own to fight for Athena.',
    poster_path: '/dhtiYYbob8saEUFWle3aWgVY28M.jpg',
    media_type: 'tv',
    genre_ids: [16, 18, 10759],
    popularity: 141.129,
    first_air_date: '1986-10-11',
    vote_average: 8.5,
    vote_count: 1057,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/zlAzK5qjpP77lPGYKDG0j6SfcDA.jpg',
    id: 38559,
    name: 'Level E',
    original_language: 'ja',
    original_name: 'レベルE',
    overview:
      "Earth has been populated by thousands of aliens from all over the galaxy. While all the other aliens are aware of their presence, it is a secret only from the Earthlings. Baka, the prince of the planet Dogra, crash lands on Earth and loses his memory. He forcibly moves in with Yukitaka Tsutsui, a first year high school student who had just moved out on his own. The normal life he once knew is quickly pulled away as he becomes the target of the prince's torment.",
    poster_path: '/tdhOYnrkZhSr6wiLDWOKIozRhEI.jpg',
    media_type: 'tv',
    genre_ids: [16, 35, 18, 10765, 10759],
    popularity: 6.815,
    first_air_date: '2011-01-11',
    vote_average: 7.859,
    vote_count: 46,
    origin_country: ['JP'],
  },
  {
    adult: false,
    backdrop_path: '/mnNkpQ4J9bNubFQfReaI9SVV9QR.jpg',
    id: 80504,
    name: 'Yuuna and the Haunted Hot Springs',
    original_language: 'ja',
    original_name: 'ゆらぎ荘の幽奈さん',
    overview:
      "Kogarashi has the ability to see supernatural, and has been possessed by ghosts since he was a kid but now he has learned to fight back against them! Unfortunately, he's now also very poor, homeless, and hoping for a happier, more normal, high school life. In his search for housing, he's introduced to a very cheap boarding house called Yuragi Manor, which was formerly a hot springs inn. It's so cheap because the house is haunted by the spirit of a high school student whose corpse was found there.\n\nKogarashi doesn't think this is going to be a problem for him. Soon he finds that Yuragi Manor's ghost is a 16-year-old girl named Yuna, who lives in his room. Kogarashi has no desire to hurt a ghost girl, and instead he ends up agreeing to help her to figure out her unfinished business so that she can move onto the afterlife before turning evil. Once it is clear that he is fine with Yuna, the other tenants reveal their own secrets—his life in Yuragi Manor is going to be far from ordinary!",
    poster_path: '/fuZemw0UoF8aMD77FSmDom3VvW1.jpg',
    media_type: 'tv',
    genre_ids: [10759, 10765, 16, 35],
    popularity: 18.431,
    first_air_date: '2018-07-14',
    vote_average: 7.481,
    vote_count: 26,
    origin_country: ['JP'],
  },
];
